# Generated by Django 6.0.3 on 2026-03-20 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_filename', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField()),
                ('resume_text', models.TextField()),
                ('match_score', models.FloatField()),
                ('matched_skills', models.TextField()),
                ('missing_skills', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
